# Interactive component
<script src="https://d3js.org/d3.v7.js"></script>
<div id="mysvg"></div>

<input type="range" min="1" max="3" value="1" class="slider" id="mybar">

<p>
<b>Survey time period <span id="period"></span></b>
</p>
<script src="script\myjs.js"></script>

We generate a interactive component to show the distributions of attractiveness rating during three period of time (before speeding dating, one day after speed dating, and three weeks after speed dating). The slidebar below allows the graph to display the distribution at different period of time. For all three time periods, participants were asked to distribute 100 points among attractiveness, intelligence, sincerity, fun, ambition, and shared interests. 
We can notice from this interactive plot that the distributions for attractiveness rating are roughly the same for three time periods. However, we can see an obvious increase in the proportion of participants who rate attractiveness between 50 and 60 (which is more than 50% of 100 points) during the third time period. This increase creates another mode in the distribution of attractiveness rating during the third period. It will be interesting to look into the reason behind the increase in attractiveness rating over time. 
